[ 2025-07-11 17:09:07,401 ] - 74 - INFO - Started data ingestion
[ 2025-07-11 17:09:16,896 ] - 52 - INFO - Spliiting the data as train and test set started
[ 2025-07-11 17:09:16,896 ] - 54 - INFO - Spliiting the data as train and test set ended
[ 2025-07-11 17:09:16,896 ] - 62 - INFO - Exporting train and test file path
[ 2025-07-11 17:09:17,449 ] - 65 - INFO - Exported train and test file path
[ 2025-07-11 17:09:17,706 ] - 33 - INFO - Number of columns 2
[ 2025-07-11 17:09:17,706 ] - 34 - INFO - Dataframe has 50 number of columns
[ 2025-07-11 17:09:17,706 ] - 103 - INFO - error occured in python script [D:\Network Security\networksecurity\components\data_validation.py] line number [81] error message [cannot access local variable 'error_message' where it is not associated with a value]
[ 2025-07-11 17:09:17,708 ] - 22 - INFO - error occured in python script [D:\Network Security\main.py] line number [19] error message [error occured in python script [D:\Network Security\networksecurity\components\data_validation.py] line number [81] error message [cannot access local variable 'error_message' where it is not associated with a value]]
