[ 2025-07-11 17:28:46,733 ] - 74 - INFO - Started data ingestion
[ 2025-07-11 17:29:19,080 ] - 52 - INFO - Spliiting the data as train and test set started
[ 2025-07-11 17:29:19,080 ] - 54 - INFO - Spliiting the data as train and test set ended
[ 2025-07-11 17:29:19,080 ] - 62 - INFO - Exporting train and test file path
[ 2025-07-11 17:29:19,400 ] - 65 - INFO - Exported train and test file path
[ 2025-07-11 17:29:19,412 ] - 11 - INFO - error occured in python script [D:\Network Security\networksecurity\utils\main_utils\utils.py] line number [9] error message [while parsing a block collection
  in "data_schema\schema.yaml", line 2, column 1
expected <block end>, but found '?'
  in "data_schema\schema.yaml", line 102, column 1]
[ 2025-07-11 17:29:19,413 ] - 19 - INFO - error occured in python script [D:\Network Security\networksecurity\components\data_validation.py] line number [17] error message [error occured in python script [D:\Network Security\networksecurity\utils\main_utils\utils.py] line number [9] error message [while parsing a block collection
  in "data_schema\schema.yaml", line 2, column 1
expected <block end>, but found '?'
  in "data_schema\schema.yaml", line 102, column 1]]
[ 2025-07-11 17:29:19,413 ] - 22 - INFO - error occured in python script [D:\Network Security\main.py] line number [18] error message [error occured in python script [D:\Network Security\networksecurity\components\data_validation.py] line number [17] error message [error occured in python script [D:\Network Security\networksecurity\utils\main_utils\utils.py] line number [9] error message [while parsing a block collection
  in "data_schema\schema.yaml", line 2, column 1
expected <block end>, but found '?'
  in "data_schema\schema.yaml", line 102, column 1]]]
